### ISSUE TITLE
reTerminal DM support

### ISSUE THREAD

**Issue by hugokernel** [Seeed-Studio/Seeed_Python_ReTerminal#4]
Hi,

The reTerminal DM will be supported ?

Thank you

**Comment by bigbearishappy** [comment]
Actually, we don't support it till now.
What is feature details you want?

**Comment by hugokernel** [comment]
> Actually, we don't support it till now. What is feature details you want?

Be able to use this Python module on both the reTerminal and the reTerminal DM (access to buttons, sensors, interfaces...)

**Comment by bigbearishappy** [comment]
The support steps of reTerminal DM is same as the reTerminal in this repo.
I'm wondering if you have time to add support to reTerminal DM ? 
If you can, I will support you if you have any problem in doing it~

**Comment by hugokernel** [comment]
> Me: The reTerminal DM will be supported ?

One year later

> Seeed: Yes, by you.

:heart:

**Comment by baorepo** [comment]
@hugokernel  Thank you for your attention, I have moved it to the TODO list, we will support it as soon as possible.

**Comment by is-qian** [comment]
Devices such as DM have been added to the support [list](https://github.com/Seeed-Studio/Seeed_Python_RPi/pull/9), and will be updated to PyPI later.
