### ISSUE TITLE
Bluetooth is not working

### ISSUE THREAD

**Issue by ClovisCorde** [Seeed-Studio/Seeed_Python_ReTerminal#7]
Hello, I have a problem with my reTerminal and I can’t find solutions online.
I had the problem with the reTerminal powering up a blank screen after the first boot. 
So I flashed the 32 bit Raspbian-reTerminal image by following the instructions from : https://wiki.seeedstudio.com/reTerminal-FAQ/#q2-how-can-i-flash-raspberry-pi-os-which-is-originally-shipped-with-reterminal 
The reTerminal is now working great except for bluetooth.
Indeed, after the first boot I type ```sudo systemctl status bluetooth``` and I get this result :

```
bluetooth.service - Bluetooth service
     Loaded: loaded (/lib/systemd/system/bluetooth.service; enabled; vendor preset: enabled)
     Active: inactive (dead)
       Docs: man:bluetoothd(8)

Sep 20 16:35:27 tgf systemd[1]: Condition check resulted in Bluetooth service being skipped.
Sep 20 16:36:56 tgf systemd[1]: Condition check resulted in Bluetooth service being skipped.
```
So I typed ```sudo modprobe btusb``` and then started bluetooth manually, when I type ```sudo systemctl status bluetooth``` I now get this result : 
```
bluetooth.service - Bluetooth service
     Loaded: loaded (/lib/systemd/system/bluetooth.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2023-09-20 16:37:18 BST; 1s ago
       Docs: man:bluetoothd(8)
   Main PID: 1569 (bluetoothd)
     Status: "Running"
      Tasks: 1 (limit: 4164)
        CPU: 49ms
     CGroup: /system.slice/bluetooth.service
             └─1569 /usr/libexec/bluetooth/bluetoothd

Sep 20 16:37:18 tgf systemd[1]: Starting Bluetooth service...
Sep 20 16:37:18 tgf bluetoothd[1569]: Bluetooth daemon 5.55
Sep 20 16:37:18 tgf systemd[1]: Started Bluetooth service.
Sep 20 16:37:18 tgf bluetoothd[1569]: Starting SDP server
Sep 20 16:37:18 tgf bluetoothd[1569]: Bluetooth management interface 1.21 initialized
```
Now my problem is that when I type “hcitool dev” there is no device.
Also, I saw online that it could be a problem with the UART and when I type “sudo systemctl status hciuart.service” I get this result :
```
     hciuart.service - Configure Bluetooth Modems connected by UART
     Loaded: loaded (/lib/systemd/system/hciuart.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2023-09-20 16:35:49 BST; 4min 12s ago
    Process: 557 ExecStart=/usr/bin/btuart (code=exited, status=1/FAILURE)
        CPU: 68ms

Sep 20 16:35:19 tgf systemd[1]: Starting Configure Bluetooth Modems connected by UART...
Sep 20 16:35:49 tgf btuart[625]: Initialization timed out.
Sep 20 16:35:49 tgf btuart[625]: bcm43xx_init
Sep 20 16:35:49 tgf systemd[1]: hciuart.service: Control process exited, code=exited, status=1/FAILURE
Sep 20 16:35:49 tgf systemd[1]: hciuart.service: Failed with result 'exit-code'.
Sep 20 16:35:49 tgf systemd[1]: Failed to start Configure Bluetooth Modems connected by UART.
```
Does anyone have a solution for this? My goal is to be able to scan bluetooth devices around the reTerminal. 

I bought a Bluetooth adapter : Asus USB-BT500 and plugged it to the reTerminal, it is recognized and I can scan bluetooth devices.
Does that mean that I have problem with the hardware in reTerminal or maybe I need to change some configurations in order to use bluetooth with the ReTerminal's hardware ?
Thanks

**Comment by matsujirushi** [comment]
Hi,
This repository is a Python library which enables you to use the onboard hardware on the reTerminal and reTerminal Bridge.
It looks like your issue has nothing to do with this repository.

For information regarding reTerminal, please contact [Tech Support & Product Discussion](https://wiki.seeedstudio.com/Getting_Started#tech-support--product-discussion).

**Comment by Thabiso-Hub** [comment]
I also have a problem with the Bluetooth after updating to Sonoma on iMac desktop, Bluetooth doesn't work anymore can't use keyboard & mouse any ides what might be the issue?
